version: "2"
services:
  plex:
    image: linuxserver/plex:latest
    container_name: plex
    hostname: frias-plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=public
      - UMASK_SET=022 #optional
      #- PLEX_CLAIM=claim-typ7xBEWxZ1HABj1QXQw
    volumes:
      - /mnt/hdd1/.plex/config:/config
      - /mnt/hdd1/media:/media
    restart: unless-stopped

  transmission:
    image: linuxserver/transmission
    container_name: transmission
    hostname: transmission
    ports:
      #- 9091:9091/tcp
      - 51413:51413/tcp
      - 51413:51413/udp
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Singapore
      - TRANSMISSION_WEB_HOME=/combustion-release/ #optional
      #- TRANSMISSION_WEB_HOME=/transmission-web-control/ #optional
    volumes:
      - /mnt/hdd1/.transmission/config:/config
      - /mnt/hdd1/downloads:/downloads
      - /mnt/hdd1/.transmission/watch:/watch
      - ./remove-finished.sh:/remove-finished.sh
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    hostname: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Singapore
      - UMASK_SET=022 #optional
    volumes:
      - /mnt/hdd1/.radarr/config:/config
      - /mnt/hdd1/media/movies:/movies
      - /mnt/hdd1/downloads:/downloads
    restart: unless-stopped
    
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    hostname: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Singapore
      - UMASK_SET=022 #optional
    volumes:
      - /mnt/hdd1/.sonarr/config:/config
      - /mnt/hdd1/media/tvseries:/tv
      - /mnt/hdd1/downloads:/downloads
    restart: unless-stopped

  bazarr:
    image: linuxserver/bazarr:development
    container_name: bazarr
    hostname: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Singapore
      - UMASK_SET=022 #optional
    volumes:
      - /mnt/hdd1/.bazarr/config:/config
      - /mnt/hdd1/media/movies:/movies
      - /mnt/hdd1/media/tvseries:/tv
    restart: unless-stopped

  jackett:
    image: linuxserver/jackett:latest
    container_name: jackett
    hostname: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Singapore
    volumes:
      - /mnt/hdd1/.jackett/config:/config
      - /mnt/hdd1/downloads:/downloads
    restart: unless-stopped
    
  nginx:
    image: nginx
    container_name: nginx
    hostname: rproxy
    ports:
      - 80:80/tcp
    volumes:
      - ./reverse-proxy.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
