all:
  hosts:
    192.168.20.25:  

  vars:
    ansible_user: pi
    ansible_python_interpreter: python3
    dns_hostnames: 
      - ip:  192.168.20.25
        hostnames:
          - rpi4.cloud
          - test.rpi4.cloud