all:
  hosts:
    192.168.20.25:  
      dns_hostnames: 
        - ip:  192.168.20.25
          hostnames:
            - rpi4.cloud
            - test.rpi4.cloud
      drives:
        - path: /mnt/hdd1
          filesystem: xfs
          src: UUID=b15ec250-9d1b-4a70-852d-59a82b441667
        # - path: /mnt/hdd2
        #   filesystem: ntfs
        #   src: abac
  vars:
    ansible_user: pi
    ansible_python_interpreter: python3

