---
- hosts: all

  tasks:
    # - name: Run apt update
    #   command: apt update
    #   become: true

    # - name: Install tools
    #   include_tasks: ./tasks/check_and_install.yml
    #   loop:
    #     - vim
    #     - telnet

    # - name: Check if Docker is installed
    #   command: docker --version
    #   register: try_run_docker
    #   ignore_errors: yes

    # - name: Install Docker
    #   include_tasks: ./tasks/install_docker.yml
    #   when: try_run_docker is failed

    - name: Mount ntfs hdd
      include_tasks: ./tasks/mount-ntfs.yml

    - name: Docker applications
