---
- hosts: all

  force_handlers: true

  vars:
    apps_to_restart: []
    apps_to_stop: []

  tasks:
    # - name: Install tools
    #   apt:
    #     name:
    #       - vim
    #       - telnet
    #     update_cache: yes
    #   become: true

    # - name: Check if Docker is installed
    #   command: docker --version
    #   register: try_run_docker
    #   ignore_errors: yes

    # - name: Install Docker
    #   include_tasks: ./tasks/install_docker.yml
    #   when: try_run_docker is failed

    # - name: Mount ntfs hdd
    #   include_tasks: ./tasks/mount_ntfs.yml

    - name: Install Node Exporter
      include_tasks: ./tasks/install_node_exporter.yml
      vars:
        node_exporter_version: "1.0.1"

    - name: Run Docker applications
      include_tasks: ./tasks/run_docker_compose.yml


  handlers:
    - name: Run Docker Compose
      docker_compose:
        project_name: Raspberry Media Server
        project_src: ~/.ansible/compose/
        remove_orphans: true

    - name: Wait until config files are created
      wait_for:
        timeout: 10
      listen:
        - Run Docker Compose

    - import_tasks: handlers/stop_services.yml
    - import_tasks: handlers/restart_services.yml
