- name: Download and extract node_exporter package
  unarchive:
    src:  "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-armv7.tar.gz"
    dest: ./
    remote_src: yes

- name: Copy node_exporter exe to /usr/local/bin
  copy:
    src: "./node_exporter-{{ node_exporter_version }}.linux-armv7/node_exporter"
    dest: /usr/local/bin/
    remote_src: yes
    mode: a+x
  become: true

- name: Create systemd service file for node exporter
  copy:
    dest: /etc/systemd/system/nodeexporter.service
    content: |
      [Unit]
      Description=NodeExporter

      [Service]
      TimeoutStartSec=0
      ExecStart=/usr/local/bin/node_exporter

      [Install]
      WantedBy=multi-user.target
  become: true

- name: Make sure node_exporter service is running
  systemd:
    state: started
    name: nodeexporter
    daemon_reload: yes
    enabled: yes
  become: true