- name: Install ntfs-3g
  apt:
    name:
      - ntfs-3g
  become: true

- name: Create a disk mount directory
  file:
    path: "{{ item.path }}"
    state: directory
    mode: '0755'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  become: true

## Mount internal Windows partition with linux compatible permissions,
## i.e. 755 for directories (dmask=022) and 644 for files (fmask=133)
## more reading: https://wiki.archlinux.org/index.php/NTFS-3G

- name: Add entry in /etc/fstab
  mount:
    path: "{{ item.path }}"
    src: "{{ item.src }}"
    fstype: ntfs-3g
    state: mounted
    opts: uid=pi,gid=pi,dmask=022,fmask=133, exec
  become: true
