- name: Install python3-distutils
  include_tasks: ./tasks/check_and_install.yml
  loop:
    - python3-distutils

- name: Check if pip is installed
  command: pip --version
  register: try_run_pip
  ignore_errors: yes

- name: Install pip
  include_tasks: ./tasks/install_pip.yml
  when: try_run_pip is failed

- name: Install Docker Compose requirements
  pip:
    name:
      - PyYAML
      - docker
      - docker-compose

- name: Copy nginx config to remote
  copy:
    src: ./config/nginx.conf
    dest: /mnt/hdd1/.nginx/config/
  notify: Restart nginx

- name: Copy transmission config to remote
  copy:
    src: ./config/transmission.json
    dest: /mnt/hdd1/.transmission/config/settings.json
  notify: Restart transmission

- name: Copy docker-compose.yml to remote
  copy:
    src: ./config/docker-compose.yml
    dest: ~/.ansible/compose/
  notify: Run Docker Compose

