- name: Install required tools
  apt:
    name:
      - python3-distutils
      - python3-venv
      - python3-pip
      - libxslt-dev
  become: true

- name: Install Docker Compose requirements
  pip:
    name:
      - PyYAML
      - docker
      - docker-compose
      - lxml

- name: Create pihole config directories
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - ~/.pihole/etc-pihole
    - ~/.pihole/etc-dnsmasq.d

- name: Copy docker-compose.yml to remote
  copy:
    src: ./config/docker-compose.yml
    dest: ~/.ansible/compose/
  notify: Run Docker Compose

- meta: flush_handlers # run compose if needed

# config management

- name: Copy nginx config to remote
  copy:
    src: ./config/nginx.conf
    dest: /mnt/hdd1/.nginx/config/
  notify: Set nginx to restart

- name: Edit transmission config
  include_tasks: config/transmission.yml

- name: Edit pihole dns config
  include_tasks: config/pihole-dns.yml

- name: Edit radarr server settings
  include_tasks: config/radarr.yml

- name: Edit sonarr server settings
  include_tasks: config/sonarr.yml

- name: Edit jackett server settings
  include_tasks: config/jackett.yml

- name: Edit bazarr server settings
  include_tasks: config/bazarr.yml
