- name: Install required tools
  apt:
    name: 
      - python3-distutils
      - python3-venv 
      - python3-pip
      - libxslt-dev
  become: true

- name: Install Docker Compose requirements
  pip:
    name:
      - PyYAML
      - docker
      - docker-compose
      - lxml

- name: Copy docker-compose.yml to remote
  copy:
    src: ./config/docker-compose.yml
    dest: ~/.ansible/compose/
  notify: Run Docker Compose

- meta: flush_handlers # run compose if needed

# config management

- name: Wait until config files are created
  wait_for:
    timeout: 10

- name: Copy nginx config to remote
  copy:
    src: ./config/nginx.conf
    dest: /mnt/hdd1/.nginx/config/
  notify: Set nginx to restart

- name: Copy transmission config to remote
  copy:
    src: ./config/transmission.json
    dest: /mnt/hdd1/.transmission/config/settings.json
  notify: Set transmission to restart

- name: Edit radarr server settings
  include_tasks: config/radarr.yml

- name: Edit sonarr server settings
  include_tasks: config/sonarr.yml

- name: Edit jackett server settings
  include_tasks: config/jackett.yml

- name: Edit bazarr server settings
  include_tasks: config/bazarr.yml
