# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'
    metrics_path: '/prometheus/metrics'
    static_configs:
    - targets: ['localhost:9090']

  - job_name: 'node_exporter'
    static_configs:
    - targets: ['172.17.0.1:9100'] # connecting to rpi host itself

  - job_name: 'grafana'
    metrics_path: '/grafana/metrics'
    dns_sd_configs:
    - names:
      - 'grafana'
      type: 'A'
      port: 3000

  - job_name: 'services_status'
    metrics_path: /probe
    params:
     module: [tcp_connect]
    static_configs:
      - targets:
        - transmission:9091
        - radarr:7878
        - sonarr:8989
        - jackett:9117
        - bazarr:6767
        - grafana:3000
        - pihole:80
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115
      