version: '2.3'
services:
  plex:
    image: linuxserver/plex:latest
    container_name: plex
    hostname: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Manila
      - VERSION=public
    volumes:
      - /mnt/hdd1/.plex/config:/config
      - /mnt/hdd1/Music:/media/Music
      - /mnt/hdd1/Video/movies:/media/Movies
      - /mnt/hdd1/Video/tv_series:/media/TV Shows
    restart: unless-stopped

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - /mnt/hdd1/.nginx/config/nginx.conf:/etc/nginx/conf.d/default.conf
    command: [nginx-debug, '-g', 'daemon off;']
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Manila
    volumes:
      - /mnt/hdd1/.radarr/config:/config
      - /mnt/hdd1:/disk/hdd1
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Manila
    volumes:
      - /mnt/hdd1/.sonarr/config:/config
      - /mnt/hdd1:/disk/hdd1
    ports:
      - 8989:8989
    restart: unless-stopped

  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Manila
    volumes:
      - /mnt/hdd1/.jackett/config:/config
      - /mnt/hdd1/torrent_temp:/Downloads
    restart: unless-stopped

  bazarr:
    image: linuxserver/bazarr
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Manila
    volumes:
      - /mnt/hdd1/.bazarr/config:/config
      - /mnt/hdd1:/disk/hdd1
    restart: unless-stopped

  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    environment:
      TZ: Asia/Manila
      VIRTUAL_HOST: 'rpi4.cloud'
    volumes:
      - ~/.pihole/etc-pihole/:/etc/pihole/
      - ~/.pihole/etc-dnsmasq.d/:/etc/dnsmasq.d/
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 67:67/udp
      - 8080:80/tcp
    dns:
      - 127.0.0.1
      - 1.1.1.1
    restart: unless-stopped

  # raspotify:
  #   image: levikleinm/raspotify-docker
  #   container_name: raspotify
  #   network_mode: host
  #   environment:
  #     BITRATE: 320
  #     DEVICE_NAME: "Raspberry Pi 4"
  #   devices:
  #     - /dev/snd:/dev/snd
  #   restart: unless-stopped

  # nettools:
  #   image: levikleinm/alpine-nettools
  #   container_name: nettools
  #   restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ~/.prometheus/etc-prometheus/:/etc/prometheus/
      - ~/.prometheus/data:/data
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/data
      - --storage.tsdb.retention.size=1GB
      - --web.console.libraries=/opt/prometheus/console_libraries
      - --web.console.templates=/opt/prometheus/consoles
      - --web.route-prefix=/prometheus
    user: "1000"
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - ~/.grafana/:/var/lib/grafana
    environment:
      GF_SERVER_ROOT_URL: http://192.168.20.25/grafana
      GF_SERVER_SERVE_FROM_SUB_PATH: 'true'
    user: "1000"
    restart: unless-stopped

  blackbox-exporter:
    image: prom/blackbox-exporter:latest
    container_name: blackbox-exporter
    volumes:
      - ~/.blackbox_exporter:/config
    command:
      --config.file=/config/blackbox-exporter.yml
    ports:
      - 9115:9115
    restart: unless-stopped
    privileged: true #for ICMP

  homeassistant:
    image: homeassistant/raspberrypi4-homeassistant:stable
    container_name: homeassistant
    volumes:
      - ~/.homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
    network_mode: host
    restart: unless-stopped

  transmission:
    image: haugene/transmission-openvpn
    container_name: transmission
    ports:
      - '9091:9091'
    cap_add:
      - NET_ADMIN
    volumes:
        - /mnt/hdd1/torrent_temp:/data
        - /mnt/hdd1/.transmission/config/settings.json:/data/transmission-home/settings.json
        - /mnt/hdd1/torrent_temp:/Downloads
        - /mnt/hdd1/.transmission/watch:/watch
    environment:
        - OPENVPN_PROVIDER=NORDVPN
        - NORDVPN_COUNTRY=hk
        - NORDVPN_CATEGORY=P2P
        - NORDVPN_CATEGORY=tcp
        - OPENVPN_USERNAME={{ nordvpn_user }}
        - OPENVPN_PASSWORD={{ nordvpn_pw }}
        - LOCAL_NETWORK=192.168.20.0/24
        - PUID=1000
        - PGID=1000
        - TZ=Asia/Manila
        - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60 --pull-filter ignore ping
        - TRANSMISSION_WEB_UI=combustion
    logging:
        driver: json-file
        options:
            max-size: 10m
    restart: unless-stopped