version: '2.3'
services:
  plex:
    image: linuxserver/plex:latest
    container_name: plex
    hostname: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Manila
      - VERSION=public
    volumes:
      - /mnt/hdd1/.plex/config:/config
      - /mnt/hdd1/Music:/media/Music
      - /mnt/hdd1/Video/movies:/media/Movies
      - /mnt/hdd1/Video/tv series:/media/TV Shows
    restart: unless-stopped

  transmission:
    image: linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Manila
      - TRANSMISSION_WEB_HOME=/combustion-release/ #options: /combustion-release/, /kettu/, /transmission-web-control/
    volumes:
      - /mnt/hdd1/.transmission/config:/config
      - /mnt/hdd1/torrent_temp:/Downloads
      - /mnt/hdd1/.transmission/watch:/watch
    ports:
      - 51413:51413/tcp
      - 51413:51413/udp
    restart: unless-stopped

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - /mnt/hdd1/.nginx/config/nginx.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Manila
    volumes:
      - /mnt/hdd1/.radarr/config:/config
      - /mnt/hdd1:/disk/hdd1
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Manila
    volumes:
      - /mnt/hdd1/.sonarr/config:/config
      - /mnt/hdd1:/disk/hdd1
    ports:
      - 8989:8989
    restart: unless-stopped

  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Manila
    volumes:
      - /mnt/hdd1/.jackett/config:/config
      - /mnt/hdd1/torrent_temp:/Downloads
    restart: unless-stopped

  bazarr:
    image: linuxserver/bazarr
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Manila
    volumes:
      - /mnt/hdd1/.bazarr/config:/config
      - /mnt/hdd1:/disk/hdd1
    restart: unless-stopped

  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    environment:
      TZ: Asia/Manila
      VIRTUAL_HOST: 'rpi4.cloud'
    volumes:
      - ~/.pihole/etc-pihole/:/etc/pihole/
      - ~/.pihole/etc-dnsmasq.d/:/etc/dnsmasq.d/
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 67:67/udp
      - 8080:80/tcp
    dns:
      - 127.0.0.1
      - 1.1.1.1
    restart: unless-stopped

  raspotify:
    image: levikleinm/raspotify-docker
    container_name: raspotify
    network_mode: host
    environment:
      BITRATE: 320
      DEVICE_NAME: "Raspberry Pi 4"
    devices:
      - /dev/snd:/dev/snd
    restart: unless-stopped

  nettools:
    image: levikleinm/alpine-nettools
    container_name: nettools
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ~/.prometheus/etc-prometheus/:/etc/prometheus/
      - ~/.prometheus/data:/data
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/data
      - --storage.tsdb.retention.size=1GB
      # - --web.route-prefix=prometheus
      # - --web.external-url=localhost:9090/prometheus
    user: "1000"
