- name: Wait until sonarr server settings is created
  wait_for:
    path: /mnt/hdd1/.sonarr/config/config.xml

- name: Set UrlBase in sonarr server settings
  xml:
    path: /mnt/hdd1/.sonarr/config/config.xml
    xpath: /Config/UrlBase
    value: sonarr
  notify: Set sonarr to restart

- name: Extract API key from sonarr server settings
  xml:
    path: /mnt/hdd1/.sonarr/config/config.xml
    xpath: /Config/ApiKey
    content: text
  register: sonarr_config
